### ISSUE TITLE
ResourceWarning: unclosed <ssl.SSLSocket 

### ISSUE THREAD

**Issue by leandropls** [jschneier/django-storages#17] opened 2015-01-19 03:09 UTC
I keep getting this error:

(...) /lib/python3.4/site-packages/boto/connection.py:1017: ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET, type=SocketType.SOCK_STREAM, proto=6, laddr=('192.168.43.100', 61734)
  ex = e

Have anyone seen it?

**Comment by synotna** [comment] 2015-01-19 15:08
I'm setting up for the first time and also got this error, it went away when I changed my AWS_STORAGE_BUCKET_NAME to the arn:aws:s3:::BUCKET_NAME format

Now I get socket.gaierror: [Errno -2] Name or service not known after a minute or two waiting instead :)

**Comment by synotna** [comment] 2015-01-19 15:49
That's a warning, the error is

**Comment by synotna** [comment] 2015-01-19 15:57
Are you also using Frankfurt? I just came across these

https://github.com/boto/boto/issues/2741
https://github.com/wal-e/wal-e/issues/152

**Comment by jschneier** [comment] 2015-01-20 21:24
@synotna ugh that boto issue is a mess. Let me think a bit about workarounds for it although I think it is separate from this issue.

@leandropls that is a separate issue, I'll do some investigation, need to run with warnings enabled all the time.

**Comment by synotna** [comment] 2015-01-21 08:50
As far as  I can tell, the warning is caused by the SSL error. 

If you do not use Frankfurt, you do not get the SSL error (which comes after the warning), and do not get the warning.

**Comment by leandropls** [comment] 2015-01-21 10:51
I'm in sa-east-1, actually.

**Comment by synotna** [comment] 2015-01-21 11:48
Nevermind then, apologies :)!

**Comment by leandropls** [comment] 2015-01-21 11:53
No problem. As I understand from the issue in Boto, there's a rollout of a new version of the API going on with S3. Possibly, sa-east-1 also got it ahead of US endpoints, just like Frankfurt.

**Comment by synotna** [comment] 2015-01-22 15:10
Ireland is now bugging out too, grr

Is there *no* way to use s3 on these regions? In the boto thread they said "After talking to their support they do say that is essentially the only way right now but they want to try and make it more streamlined like the rest of their regions" - that was in November, and nothing has gotten better, only more regions are getting worse.

Or is the solution to move everything to us-east-1 and wait until the same happens there? :(

**Comment by jschneier** [comment] 2015-01-22 17:24
@synotna realistically speaking this *should* be handled by boto, that's the purpose of the library. If I don't see any movement on it in the very near future I guess we'll have a go at implementing SigV4 as detailed [here](http://docs.aws.amazon.com/general/latest/gr/sigv4-signed-request-examples.html).

**Comment by pikeas** [comment] 2015-05-23 23:33
Any movement on this?

**Comment by coderbounty-cowboy** [comment] 2016-12-04 20:39
I'd like to see this get closed, anyone want to put a bounty? www.coderbounty.com

**Comment by jschneier** [comment] 2017-03-01 19:29
Going to close this and suggest anyone who runs across this move to the boto3 backend.

**Closed by jschneier** 2017-03-01 19:29 UTC
