### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'complete'

### ISSUE THREAD

**Issue by MuslimBeibytuly** [jschneier/django-storages#1293] opened 2023-09-05 03:58 UTC
```
    with default_storage.open(
  File "/usr/local/lib/python3.11/site-packages/django/core/files/base.py", line 106, in __exit__
    self.close()
  File "/usr/local/lib/python3.11/site-packages/storages/backends/s3boto3.py", line 230, in close
    self._multipart.complete(
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'complete'
```

**Comment by jschneier** [comment] 2023-09-05 04:08
Is his a dupe of https://github.com/jschneier/django-storages/issues/1256? Do you want to attempt to fix? Not sure why this would happen more often now.

**Closed** 2023-09-10 00:10 UTC
