### ISSUE TITLE
specify additional metadata for google storage

### ISSUE THREAD

**Issue by bd** [jschneier/django-storages#663] opened 2019-02-06 21:54 UTC
I'd really like to be able to set arbitrary metadata/headers when new files get uploaded to google storage. Ideally, i'd have arbitrary keyword args on my `FileField` so I could, for example, set the `content-type` and `content-disposition` fields during the upload. It's not clear to me if that's supported by the google api, though. 

This one seems related, https://github.com/jschneier/django-storages/issues/231

**Comment by martey** [comment] 2019-09-25 21:13
I think this is a duplicate of #510.

**Comment by JeongsangBaek** [comment] 2019-12-09 10:34
This is a workaround for me. GoogleCloudStorage class sets content_type of blob using GoogleCloudFile.mime_type and it is set by mimetypes.guess_type. You can set content-type by mimetypes.add_type() like below:

`           claim_attachment = ClaimAttachment()

            # Django-storage set content-type by using mimetypes.guess_type() so that add_type for .txt
            mimetypes.add_type('text/plain;charset=UTF-8', '.txt')
            claim_attachment.detected_text.save(dest_text_url, ContentFile(str.encode(detected_text)))
            claim_attachment.save()`

**Closed** 2021-09-20 03:46 UTC
Labels: google
