### ISSUE TITLE
File upload to AWS fails but record is still created in Django (using Wagtail)

### ISSUE THREAD

**Issue by mwharrison** [jschneier/django-storages#221] opened 2016-10-27 16:04 UTC
I am using django-storages to upload media and static files to S3. If a user uploads a file, and it fails, the record is created in Django, but clicking on it throws a 500 error.
Is this something I have configured incorrectly? It seems like the upload process should be transactional and roll back creating a database record if the upload fails.

Thanks!

**Comment by vstoykov** [comment] 2016-11-10 14:18
If you provide traceback then will be easier for maintainers (or something else) to tell you where is the problem and eventually to prepare a fix if the problem is in django-storages.

**Comment by jschneier** [comment] 2017-01-12 19:10
Please provide your configuration or a traceback. Preferably both. Since this issue has been open a while without extra info added I'm going to close it.

**Closed by jschneier** 2017-01-12 19:10 UTC

**Comment by mwharrison** [comment] 2017-01-12 19:39
Sorry! I didn't see the comment from @vstoykov! I don't have an example right now of the traceback - but it's basically the file exists in the Django DB but does not exist in S3 bucket.
Here is my configuration file: https://github.com/openstax/openstax-cms/blob/master/openstax/custom_storages.py
