### ISSUE TITLE
Relative CSS path does not work with GCS 

### ISSUE THREAD

**Issue by zamai** [jschneier/django-storages#454] opened 2018-01-21 16:00 UTC
Hi,
After switching to `.gcloud.GoogleCloudStorage` my  do not resolve, instead they get redirected to wrong google domain.
 
The static files from the HTML templates are rendered fine, but the relative CSS urls `url(../img/icons/fon.png)` within the css file get redirected to:
https://storage.googleapis.com/path-to-the-file 
instead of:
https://storage.googleapis.com/**mybucket-name**/path-to-the-file
Screenshots of the browser request and the CSS file.
![image](https://user-images.githubusercontent.com/10281047/35195991-65b95572-fecc-11e7-83c1-879226c8dc2d.png)
![image](https://user-images.githubusercontent.com/10281047/35195992-6aacc4b0-fecc-11e7-8621-91b298c75262.png)

My Django settings:
```
STATIC_URL = '/static/'
STATICFILES_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'
GS_BUCKET_NAME = 'cfpp-static'
GS_AUTO_CREATE_BUCKET = True
GS_AUTO_CREATE_ACL = 'publicRead'
```
Would really appreciate any advice on this, thanks!

**Comment by hillmark** [comment] 2018-01-25 09:31
+1 Also struggling with this one.

**Comment by przemokraw** [comment] 2018-01-26 14:56
+1 I have the same problem

**Comment by hillmark** [comment] 2018-01-26 14:59
Not sure that django-storages can do much about it though, as looks like it's more to do with how relative paths are resolved by Cloud Storage, so be good to hear about that side of things, if anyone has experience?

**Comment by sww314** [comment] 2018-02-18 16:30
I think this is just an issue with how GCS works. It fakes paths and does not really have folders. 
https://stackoverflow.com/questions/44308221/to-encode-or-not-to-encode-path-parts-in-gcs

**Comment by pfk-beta** [comment] 2018-02-27 12:03
I think that it is bug in django-storages. I've created simple html page, with styles file, and this style has relative path "../img/image.png", and it works. So I think that uploading files to GCS encode relative path of file, and should create relative folders.

**Comment by pfk-beta** [comment] 2018-03-12 16:47
Google has release google-cloud-storage about week ago, and the problem is solved. Just you need to change version of google-cloud-storage to 1.8.0(for now), and the problem should disappear.

**Closed** 2018-09-17 18:55 UTC
Labels: google

**Comment by noelbk** [comment] 2020-05-22 15:57
> Google has release google-cloud-storage about week ago, and the problem is solved. Just you need to change version of google-cloud-storage to 1.8.0(for now), and the problem should disappear.

That didn't work for me.  I'm not sure how to "change version of google-cloud-storage to 1.8.0".  I upgraded my gsutil and created a brand ne bucket, but still my static html page was rediected to a URL with all the path separators escaped to %2F, so all relative links broken.  How exactly do you upgrade a bucket to fix that?
