### ISSUE TITLE
Storages backend should have consistent constructors

### ISSUE THREAD

**Issue by sam-at-github** [jschneier/django-storages#154] opened 2016-06-03 06:06 UTC
Storages backends are supposed to implement [Storage](https://docs.djangoproject.com/en/dev/ref/files/storage/#the-storage-class) API right? Storage interface does not specify what the constructor should look like but the existing [FileSystemStorage](https://docs.djangoproject.com/en/dev/ref/files/storage/#the-filesystemstorage-class) takes name parameters. It would be good if all storage backends took their parameters in the same way. Use case: writing a generic UI to configure storage backends.

**Comment by EvaSDK** [comment] 2017-03-14 11:09
Looks like a duplicate of issue #25.

**Comment by jschneier** [comment] 2017-03-15 15:14
Thanks, overlooked at that. Closing as dup.

**Closed by jschneier** 2017-03-15 15:14 UTC
