### ISSUE TITLE
django-storages, dropbox and windows path issue 

### ISSUE THREAD

**Issue by AliPolat** [jschneier/django-storages#699] opened 2019-05-13 12:27 UTC
Help please :

Exception Type: | ValidationError
'D:/home/site/wwwroot/media/urunler/Koala.jpg' did not match pattern '(/(.\|[\r\n])*\|id:.*)\|(rev:[0-9a-f]{9,})\|(ns:[0-9]+(/.*)?)'

#617 (comment)

I have the exact same configuration and the same problem. Is there any way to bypass the windows path issue other than migrating to linux?

My environment
python 3.6
django 2.1
dropbox for media files
azure for deployment
windows for iis

**Comment by sww314** [comment] 2019-05-13 13:41
Duplicate of #689
This error comes from the upstream dropbox library.

I would check to see if a newer version of the library has this fixed. 
Alternatively, you could dig around in the storages code and convert the paths to a posix paths before sending it.

**Closed** 2019-05-13 13:43 UTC
Labels: bug, dropbox, duplicate

**Comment by RobKuipers** [comment] 2025-11-26 09:35
I feel this problem stems from using Django's `safe_join`  (and thus `os.path.join`) in `_full_path`

I created a simple wrapper to bypass the problem

from storages.backends.dropbox import DropBoxStorage


class FixedDropBoxStorage(DropBoxStorage):
    """
    Dropbox storage that prevents Windows from generating invalid 'C:/...' paths
    when constructing Dropbox API paths.

    Why this override exists
    ------------------------
    The original DropBoxStorage uses Django's `safe_join` (and therefore
    `os.path.join`) to build the full Dropbox path. On Windows, using a
    root_path like "/" combined with a name like "test/reports/..." causes
    `safe_join` to resolve "/" into the current drive (e.g.: "C:/"), resulting in
    paths such as:

        C:/test/reports/....

    The Dropbox API rejects these, because Dropbox paths must be POSIX-style
    paths starting with "/" (or id:/rev:/ns:), **never** Windows filesystem paths.

    This subclass bypasses safe_join entirely and manually constructs a
    POSIX-style path from `root_path` and `name`, so that the Dropbox API
    always receives a valid Dropbox-style path even when running on Windows.
    """

    def _full_path(self, name: str) -> str:
        # Normalize special cases
        if not name or name == "/":
            name = ""

        root = (self.root_path or "").strip()

        # root_path = "" or "/" means "Dropbox root"
        if root in ("", "/"):
            root = ""
        else:
            # Normalize formatting
            if not root.startswith("/"):
                root = "/" + root.lstrip("/\\")
            root = root.rstrip("/\\")

        # Normalize `name`
        name = name.lstrip("/\\") if name else ""

        # Build final Dropbox POSIX path
        if root and name:
            full = f"{root}/{name}"
        elif root:
            full = root
        elif name:
            full = "/" + name
        else:
            full = "/"

        return full


Hope this helps.
