### ISSUE TITLE
How to Get Django, Storages and Dropbox to work

### ISSUE THREAD

**Issue by dedayoa** [jschneier/django-storages#265] opened 2017-02-05 17:47 UTC
Hello Guys,
Desperate fellow here. I've done the following, but the farthest I got was this error
`dropbox.rest.ErrorResponse: [400] {'path': "Invalid path '/c:\\Users\\Dayo\\git2\\loudam\\static\\css\\animate.css': character at index 3: backslash not allowed"}`

1. Installed Storages
2. Installed the python dropbox SDK
3. Added storages to INSTALLED_APPS
4. Configured my DROPBOX_OAUTH2_TOKEN to the Generated access token
5. Configured DROPBOX_ROOT_PATH to 'static' - I really don't know what this should be

I then try to collecstatic, then I run into the error I earlier pasted.
My goal is actually to be able to upload to and serve media files from dropbox (for a site hosted on heroku)

Any help will be much appreciated.

**Comment by ZuluPro** [comment] 2017-02-09 04:24
Hello @dedayoa 
Thanks for report this issue.

Could you give us the following things:
- The traceback of the error
- Your `STATIC_ROOT`

This error appears clearly Windows-related.

**Comment by jschneier** [comment] 2017-03-01 20:03
This looks like a Windows issue

**Comment by jschneier** [comment] 2017-03-01 20:11
Ah related to #137 and #138.

**Comment by dedayoa** [comment] 2017-03-02 06:30
Hi @jschneier 
Thanks for getting back. However, I moved to Amazon S3, seeing that dropbox will be killing the public folder on the 15th anyway.
I no longer have the configurations in place.
B.R

**Comment by jschneier** [comment] 2017-03-03 17:28
@dedayoa thanks for the update. going to close this as a dupe of the above issues in that case.

**Closed by jschneier** 2017-03-03 17:28 UTC

**Comment by jhondoedo** [comment] 2019-04-09 09:15
with the same settings i am getting this is the error'D:/media/10506738_10150004552801856_220367501106153455_o.jpg' did not match pattern '(/(.|[\r\n])|id:.)|(rev:[0-9a-f]{9,})|(ns:[0-9]+(/.*)?)'
#689
