### ISSUE TITLE
No attribute 'WindowsAzureMissingResourceError' 

### ISSUE THREAD

**Issue by yarnball** [jschneier/django-storages#102] opened 2015-12-09 04:03 UTC
Hi,

I've not used django-storages with any provider. I keep getting the error 'module' object has no attribute 'WindowsAzureMissingResourceError'.

Here is the traceback http://dpaste.com/12F5D3S

Here is a snippet of my 'settings.py':

```
DEFAULT_FILE_STORAGE = 'storages.backends.azure_storage.AzureStorage'

AZURE_ACCOUNT_NAME = "account_name"

AZURE_ACCOUNT_KEY = "xxxxx"

AZURE_CONTAINER = "container_name"

MEDIA_ROOT = '/media/'

MEDIA_URL = 'stashdimages.core.windows.net/'
```

Models.py

`testfile = models.FileField("Test File", blank=True, null= True)`

**Comment by jschneier** [comment] 2016-01-23 02:30
Hi and thanks for the report. This sounds like a version issue. Can you tell me what version of azure you have installed?

**Comment by zuck** [comment] 2016-03-07 07:06
I think the problem is related with not installed dependencies.

Is **azure** Python module installed in your environment?

It seems **django-storages** doesn't automatically install it (as the **dropbox** module for **DropBoxStorage** class).

**Comment by aleccool213** [comment] 2016-10-14 22:43
If the `azure` pip package needs to be installed alongside why isnt this in the docs?

**Comment by ZuluPro** [comment] 2016-10-15 00:02
@aleccool213 As django-storage is free software, we'll be happy to receive a contribution from you about it.

**Comment by aleccool213** [comment] 2016-10-15 02:07
@ZuluPro Thought there might have been a different reason for this :) lol will do 👍

**Comment by sww314** [comment] 2018-08-23 16:00
Fixed in #565

**Closed by sww314** 2018-08-23 16:00 UTC
Labels: azure
