### ISSUE TITLE
The default storage should take OPTIONS from STORAGES if defined

### ISSUE THREAD

**Issue by PetrDlouhy** [jschneier/django-storages#1276] opened 2023-08-22 10:18 UTC
Django in version 4.2.5 fixed a bug with default staticfiles/file storages. Now it returns `settings.STORAGES["staticfiles"]["BACKEND"]` and `settings.STORAGES["default"]["BACKEND"]` for `DEFAULT_STATICFILES_STORAGE` and `DEFAULT_FILE_STORAGE` respectively. More is described in [Django issue 34773](https://code.djangoproject.com/ticket/34773).

For `django-storages` this means that storage defined by new `STORAGES` settings is returned as default, but the settings of that storage are taken from general `AWS_*` settings.
This could lead to many misunderstandings and confusion for the users, because they are expecting the configuration to be taken from the `OPTIONS` of the appropriate storage set by `STORAGES` settings.

I am experiencing this with `S3Boto3Storage`, but the same case could be for other storages.

**Comment by jschneier** [comment] 2023-08-26 19:44
Hmm, this seems like a bug in Django? Shouldn't they be instantiating the storage using `OPTIONS`?

**Comment by PetrDlouhy** [comment] 2023-08-27 13:48
@jschneier I am not sure now which side is behaving faulty now. Please take look at the [Django issue](https://code.djangoproject.com/ticket/34773) where Jarosław is trying to imply that the problem is in `django-storages` (if I got it right).

I am not sure what can I do next to get this fixed. This issue would be blocking anyone from converting to the new STORAGES and can cause misconfigurations if somebody tries to migrate.

**Comment by PetrDlouhy** [comment] 2023-08-28 10:45
I just realized that the Django 4.2.5 with the fix is not yet officially released.

I also found that there might not be anything we can do here or in Django itself to get the storages initiated correctly. For example in `django-avatar` the initialization is done by:

```python
from avatar.conf import settings

avatar_storage = get_storage_class(settings.AVATAR_STORAGE)()
```

The `get_storage_class` will receive string with storage import path, so the information that `default` or `avatar` storage alias should be used for initialization is lost.

**Comment by PetrDlouhy** [comment] 2023-08-28 10:50
But maybe `django-storages` should at least mention this behavior in documentation, because the `default` storage not taking the `OPTIONS` parameter is really not intuitive.

**Comment by cclauss** [comment] 2023-09-07 12:04
Django 4.2.5 was release a few days ago with https://code.djangoproject.com/ticket/34773 fixed.
* https://docs.djangoproject.com/en/4.2/releases/4.2.5

**Comment by jschneier** [comment] 2023-09-13 05:00
Oh the issue is with 3rd party packages that still use `DEFAULT_FILE_STORAGE`? I'm not sure there's much we can do for them in that case. Going to close this one out.

**Closed by jschneier** 2023-09-13 05:00 UTC
