### ISSUE TITLE
collectstatic is not overriding changed files

### ISSUE THREAD

**Issue by matheusjardimb** [jschneier/django-storages#134] opened 2016-04-01 02:17 UTC
collectstatic is not overriding changed files and it's related to changed date of files and timezone.
I found this issue https://bitbucket.org/david/django-storages/issues/167/collectstatic-is-not-overwriting-changed and someone recently complained about it too.

Files only get updated when I "touch" them in order to modify it's changed date to some day in the future.

I seems S3 is not sending proper changed date or the algorithm is not considering timezone

**Comment by dcloud** [comment] 2016-08-10 17:14
This looks like a duplicate of #49 (which references pr #84, fwiw).

**Comment by jschneier** [comment] 2017-03-03 18:32
Dupe #49, going to probably implement Django 1.10s logic for backward compat or else simply allow the new 1.10 api to take care of this,

**Closed by jschneier** 2017-03-03 18:32 UTC
