### ISSUE TITLE
svg mimetype for S3 content-type

### ISSUE THREAD

**Issue by campbellmc** [jschneier/django-storages#130] opened 2016-03-17 18:09 UTC
Hi,
Is there a recommended method for setting the content-type headers for .svg files on S3 to `image/svg+xml`?

Python 2.7 up to 2.7.11 doesn't have the mimetype so we get the default `application/octet-stream` on S3 (None result from `mimetypes.guess_type`)

The following code in s3boto.py works in order to register the image/svg+xml mimetype and set the content-type header.  Is this the best solution or am I missing something?

```
*** s3boto.py   2016-03-17 17:24:07.836025937 +0000
--- s3boto.py.mimetype  2016-03-17 17:23:23.639031962 +0000
***************
*** 207,212 ****
--- 207,213 ----
      secret_key = setting('AWS_S3_SECRET_ACCESS_KEY', setting('AWS_SECRET_ACCESS_KEY'))
      file_overwrite = setting('AWS_S3_FILE_OVERWRITE', True)
      headers = setting('AWS_HEADERS', {})
+     mimetypes = {}
      bucket_name = setting('AWS_STORAGE_BUCKET_NAME')
      auto_create_bucket = setting('AWS_AUTO_CREATE_BUCKET', False)
      default_acl = setting('AWS_DEFAULT_ACL', 'public-read')
***************
*** 247,252 ****
--- 248,256 ----
              if hasattr(self, name):
                  setattr(self, name, value)

+         for name, value in self.mimetypes.items():
+             mimetypes.add_type(name, value)
+
          # For backward-compatibility of old differing parameter names
          if acl is not None:
              self.default_acl = acl
```
Then include the additional mimetype settings in the S3BotoStorage lamda function:

```
    mimetypes={
        'image/svg+xml': '.svg',
    },
```

**Comment by jschneier** [comment] 2016-04-23 20:50
Hi. The following is from python 2.7.10

```python
>>> import mimetypes
>>> name = 'image.svg'
>>> mimetypes.guess_type(name)
'image/svg+xml', None)
```

Not sure where you are seeing the issue then.

**Comment by jschneier** [comment] 2016-04-23 21:15
Possibly a dupe of #24

**Comment by campbellmc** [comment] 2016-04-23 22:46
At the time, I looked at the source for python up to 2.7.11.  The mime-type may have been rolled into some distributions or could be provided on different platforms since the code does attempt to guess using other sources:  ie mimetypes.py ~
```
knownfiles = [
    "/etc/mime.types",
    "/etc/httpd/mime.types",                    # Mac OS X
    "/etc/httpd/conf/mime.types",               # Apache
    "/etc/apache/mime.types",                   # Apache 1
    "/etc/apache2/mime.types",                  # Apache 2
    "/usr/local/etc/httpd/conf/mime.types",
    "/usr/local/lib/netscape/mime.types",
    "/usr/local/etc/httpd/conf/mime.types",     # Apache 1.2
    "/usr/local/etc/mime.types",                # Apache 1.3

```
But it's not certainly not in the 2.7.5 python shipped with Centos 7.2 - and none of the additional "guess" files exist either.

I'd prefer to be more deterministic about adding image/svg+xml - rather than be at the mercy installing other packages I don't actually require or files that could be overwritten with different package installations.

**Comment by jschneier** [comment] 2016-09-14 00:32
Mmm. I'd recommend adding it to the global db that `mimetypes` uses internally then, that will get `svg` in there in general.

**Closed by jschneier** 2016-09-14 00:32 UTC

**Comment by tisdall** [comment] 2019-01-14 16:39
for anyone else stumbling across this...  It seems CentOS doesn't come with "/etc/mime.types" installed by default and you need to install a package called "mailcap".

**Comment by campbellmc** [comment] 2019-01-18 15:41
On CentOS, you can just create /etc/mime.types without having to install a package - and add one line to it:
```
image/svg+xml svg
```
