### ISSUE TITLE
Upload file without storing whem on disk first

### ISSUE THREAD

**Issue by Smosker** [jschneier/django-storages#363] opened 2017-07-24 08:10 UTC
Hello! I'm want to use a s3 storage, can you please tell me - can this module load files directly to s3 storage without storing whem localy first in some /tmp dir?

I have to work with big files and i dont want to store them localy before sending to s3 cloud.
thanks in advance for reply.

**Comment by sww314** [comment] 2018-07-12 01:20
Duplicate of #434

**Closed by sww314** 2018-07-12 01:20 UTC
